### ISSUE TITLE
(jsii) Remove Package Resolutions for `@types/babel__traverse`

### ISSUE THREAD

**Issue by mrgrain** [projen/projen#2264]
This change in DefinitelyTyped drops release for TS3.9 which is needed for jsii: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63359

Pinning `@types/babel__traverse` to `7.18.2` works for now.

Once we can, we should remove the pin.

**Comment by pchaganti** [comment]
This might be why I am getting this error on compile 

```
� compile | jsii --silence-warnings=reserved-word
[2022-11-29T17:24:08.213] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
../../../node_modules/@types/babel__traverse/index.d.ts:68:50 - error TS1005: ']' expected.

68 export type ArrayKeys<T> = keyof { [P in keyof T as T[P] extends any[] ? P : never]: P };
                                                    ~~
../../../node_modules/@types/babel__traverse/index.d.ts:68:53 - error TS1005: ';' expected.

68 export type ArrayKeys<T> = keyof { [P in keyof T as T[P] extends any[] ? P : never]: P };
                                                       ~
```

**Comment by pchaganti** [comment]
Just updated everything to latest and running into the above error. Do I pin the package in projen.rc?

thanks!

**Comment by mrgrain** [comment]
Yes likely! Thankfully it has been fixed already in projen. 🥳 
Just run `projen upgrade`.

The ticket here is only to remind us to eventually remove the override.

**Comment by pchaganti** [comment]
Ran **_projen upgrade_**. Still getting the same error on compile.

**Comment by pchaganti** [comment]
Any changes I need to do in the .projenrc?

**Comment by mrgrain** [comment]
To be honest you might have to run `projen upgrade && projen` and then do this twice, because you need to:
- First update projen
- Generate the update config
- Install new dependencies

Do you have `@types/babel__traverse` in the resolutions/overrides in your `package.json`?

What Project type are you using? (I've added the "fix" for `JsiiProject` - might have missed some others).

---

And to be clear for everyone: This is not a projen issue. Projen is just helping you to fix it.
It's an issue with Jsii and a transitive dependency.

**Comment by mrgrain** [comment]
Yes it does and worked for a bunch if my repos.

Can you double check you're on [v0.65.38](https://github.com/projen/projen/releases/tag/v0.65.38) or higher after the upgrade. 

Also please answer:
> Do you have @types/babel__traverse in the resolutions/overrides in your package.json?

**Comment by pchaganti** [comment]
I am doing it this way in .projenrc. Not sure if this is what you mean by overrides.

```
devDeps: [
    'aws-cdk-lib',
    'constructs',
    "standard-version",
    "@types/babel__traverse@7.18.2"
  ]
```

**Comment by pchaganti** [comment]
```
npx projen --version
0.65.41
```

**Comment by mrgrain** [comment]
It should look like this (or `overrides` instead of `resolutions` if you are not using yarn`
https://github.com/projen/projen/blob/3c406e1ec581e55423aafea17846347d098d65fb/package.json#L196

`devDeps` should work as well.

So are you all good now?

**Comment by pchaganti** [comment]
No. Same error still. Upgraded multiple times. Have it in devDeps as above. Using latest projen. Still no go. This is how package.json looks:

```
"resolutions": {
    "@types/prettier": "2.6.0",
    "@types/babel__traverse": "7.18.2"
  },
```

**Comment by mrgrain** [comment]
Very odd, but we can narrow it down. Try deleting your `node_modules` and `yarn.lock` and run `yarn` again.

**Comment by pchaganti** [comment]
Tried that. Still same error. Using nx-monorepo but that shouldnt have anything to do with it. 

Will try to start from scratch and create a test project and see what happens.

**Comment by pchaganti** [comment]
Attaching a clean test project that uses ```AwsCdkConstructLibrary```

Removed node_modules to reduce size. 

After running yarn, if you run ```npm run compile``` in ```base/cdk-projec-test```, you should see the types error.

[test_projen.zip](https://github.com/projen/projen/files/10124752/test_projen.zip)

**Comment by pchaganti** [comment]
![image](https://user-images.githubusercontent.com/6500/204844063-37479c0b-81f8-4811-ad30-60bdbce0d657.png)

**Comment by mrgrain** [comment]
FYI: You zipped up the `.git` folder which might reveal more than you wanted to of your project.

**Comment by mrgrain** [comment]
Found the issue. The root `NxMonorepoProject` also depends on the breaking dependency.
Because of the way node or TS or jsii works, it somehow attempts to use the (wrong) version from the root and not the correct version from `base/cdk-projen-test/node_modules`. The error message should have pointed us to that.

You'll need to add this to the `NxMonorepoProject`:
```
project.package.addPackageResolutions("@types/babel__traverse@7.18.2");
```

and raise an issue with the maintainers of `nx-monorepo` =/

**Comment by pchaganti** [comment]
You sir, are a certified wizard. Thank you!

I will raise a ticket in the nx-monorepo too and link to this.

thanks again for your help!

**Comment by GEMISIS** [comment]
Is this fixed? Seeing a bunch of errors regarding various types and seems like I'm maybe hitting this same issue?

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/3916133/210289701-0a8ab446-0952-40a3-b041-6051e8d6f631.png">

**Comment by mrgrain** [comment]
Yes, it should be fixed as far as projen can do anything about it.

It's possible you are still experiencing this with a custom configuration and might have to manually add the overrides as the PR does.

If you can share your project code, I might be able to give better pointers.
